import { ConfigProvider } from "antd"
import type { Metadata } from "next"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            components: {
              Button: {
                borderRadius: 2
              }
            },
            token: {
              // TODO: 字体
              fontFamily: "pingfang SC, helvetica neue, arial, hiragino sans gb, microsoft yahei ui, microsoft yahei, simsun, 'sans-serif'"
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
